version: "2"

# A Docker Compose file for configuration of the production environment

services:
  lb:
    extends:
      file: docker-compose-common.yml
      service: lb
    image: crakkerjak/idb_lb
    environment:
      # Always deploy to n1 so the lb always has the same IP address. This is
      # just for convenience and isn't strictly necessary.
      - "constraint:node==*n1"
    env_file:
      - idb-mysql-root-prod.env


  app:
    extends:
      file: docker-compose-common.yml
      service: app
    image: crakkerjak/idb_app
    expose:
      # Expose port 8000 so it's only visibile on the container, not the host
      - "8000"
    # env_file: pythonwebapp-mysql-prod.env
    command: gunicorn idb:app --bind 0.0.0.0:8000
      # Run Gunicorn to serve app requests

  db:
    extends:
      file: docker-compose-common.yml
      service: db
    image: crakkerjak/idb_db
    expose:
      # Expose port 3306 so it's only visibile on the container, not the host
      - "3306"
    env_file:
      - idb-mysql-prod.env
      - idb-mysql-root-prod.env
    volumes_from:
      # Mount the volumes from the data container to store our MySQL files
      - data

  data:
    extends:
      file: docker-compose-common.yml
      service: data

networks:
  backend: {}
